---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - dataprepper.kaasops.io
  resources:
  - dataprepperdefaults
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataprepper.kaasops.io
  resources:
  - dataprepperpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - dataprepper.kaasops.io
  resources:
  - dataprepperpipelines/status
  - datapreppersourcediscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataprepper.kaasops.io
  resources:
  - datapreppersourcediscoveries
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
